name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 2403a987-c890-4677-8cd6-ca9f01ad806b
          heroku_app_name: "agile-thicket-48649" #Must be unique in Heroku
          heroku_email: "kuttukuttan126@gmail.com"
